#Import libraries


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

#Import dataset

In [ ]:
dataset = pd.read_csv('PlayStore_reviews.csv')

In [ ]:
dataset.head(50)

App  ... Sentiment_Subjectivity
0   10 Best Foods for You  ...               0.533333
1   10 Best Foods for You  ...               0.288462
2   10 Best Foods for You  ...                    NaN
3   10 Best Foods for You  ...               0.875000
4   10 Best Foods for You  ...               0.300000
5   10 Best Foods for You  ...               0.300000
6   10 Best Foods for You  ...               0.900000
7   10 Best Foods for You  ...                    NaN
8   10 Best Foods for You  ...               0.000000
9   10 Best Foods for You  ...               0.000000
10  10 Best Foods for You  ...               0.600000
11  10 Best Foods for You  ...               0.100000
12  10 Best Foods for You  ...               0.875000
13  10 Best Foods for You  ...               0.866667
14  10 Best Foods for You  ...               0.511111
15  10 Best Foods for You  ...                    NaN
16  10 Best Foods for You  ...               1.000000
17  10 Best Foods for You  ...               0.666667
18  10 Best Foods for You  ...               0.100000
19  10 Best Foods for You  ...               1.000000
20  10 Best Foods for You  ...               0.800000
21  10 Best Foods for You  ...               0.350000
22  10 Best Foods for You  ...               0.000000
23  10 Best Foods for You  ...               0.500000
24  10 Best Foods for You  ...               0.500000
25  10 Best Foods for You  ...               0.000000
26  10 Best Foods for You  ...               1.000000
27  10 Best Foods for You  ...               0.500000
28  10 Best Foods for You  ...               0.690000
29  10 Best Foods for You  ...               0.000000
30  10 Best Foods for You  ...               0.600000
31  10 Best Foods for You  ...               0.200000
32  10 Best Foods for You  ...               0.500000
33  10 Best Foods for You  ...               0.750000
34  10 Best Foods for You  ...               0.675000
35  10 Best Foods for You  ...               0.600000
36  10 Best Foods for You  ...               0.300000
37  10 Best Foods for You  ...               0.356313
38  10 Best Foods for You  ...               0.600000
39  10 Best Foods for You  ...               0.675000
40  10 Best Foods for You  ...               0.600000
41  10 Best Foods for You  ...               0.550000
42  10 Best Foods for You  ...               0.550000
43  10 Best Foods for You  ...               0.000000
44  10 Best Foods for You  ...               0.150000
45  10 Best Foods for You  ...               0.412500
46  10 Best Foods for You  ...               0.533333
47  10 Best Foods for You  ...               0.800000
48  10 Best Foods for You  ...               0.150000
49  10 Best Foods for You  ...               0.525000

[50 rows x 5 columns]

In [ ]:
len(dataset.iloc[:, 1].values)

30877

In [ ]:
dataset.isnull().sum().any()

True

In [ ]:
dataset = dataset.dropna()

In [ ]:
dataset.isnull().sum().any()

False

In [ ]:
len(dataset.iloc[:, 1].values)

18135

In this Notebook, we will solve some of the questions 
1. Predicting sentiments : Positive/Negative/Neutral
2. Predicting sentiment polarity
3. Predicting sentiment subjectivity

#Cleaning the Text -> Reviews

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(18135):
  tab_review = str(dataset.iloc[i, 1])
  review = re.sub('[^a-zA-z]', ' ', tab_review)
  reveiw = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
corpus

['I like eat delici food that I cook food case best food help lot also best befor shelf life',
 'thi help eat healthi exercis regular basi',
 'work great especi go groceri store',
 'best idea us',
 'best way',
 'amaz',
 'look forward app',
 'It help site It help food get',
 'good',
 'use inform the amount spell error question valid inform share onc fix star given',
 'thank great app add arthriti eye immun kidney liver detox food pleas',
 'greatest ever complet awesom maintain health thi must ppl love',
 'good health good health first prioriti',
 'health It import world either life think',
 'mr sunita bhati I thank develop make kind app realli good healthi food bodi',
 'veri use diabet age I need control sugar thank',
 'one greatest app',
 'good nice',
 'healthi realli help',
 'god health',
 'health should alway BE top prioriti ON mysg',
 'An excel A use',
 'I found lot wealth form health',
 'becaus I found import',
 'healthi eat',
 'veri good simpli good',
 'On test',
 'good',
 'thank 

Label Encoding for Sentiment

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_sentiment = le.fit_transform(dataset.iloc[:, 2].values)

In [ ]:
for i in y_sentiment:
  if i == 1:
    print("Present")
    break

Present


#Creating bag of words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_sentiment, test_size = 0.2, random_state = 0)

#Classification
.values.values.values......,,.,,...,.,.

Training the Decision Tree Classification model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 642   44  138]
 [  39  418   45]
 [ 134   60 2107]]


0.8731734215605184

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X = X_train, y= y_train, cv = 10)
accuracies.mean()

0.8680029468380903

In [ ]:
accuracies.std()

0.009143691761352091

Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
as1 = accuracy_score(y_test, y_pred)
print(cm)
print(as1)

[[ 675   49  100]
 [  19  426   57]
 [  79   68 2154]]
0.8974358974358975


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X = X_train, y= y_train, cv = 10)
accuracies.mean()

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.8908190308705055

In [ ]:
accuracies.std()

0.0047027736394988145

## Training the K-NN model on the Training set

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[ 407  276  141]
 [  11  451   40]
 [ 119  437 1745]]


0.7176730079955886

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X = X_train, y= y_train, cv = 10)
accuracies.mean()

0.7036125383207776

## Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[435 309  80]
 [ 32 438  32]
 [491 909 901]]


0.48910945685139234

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X = X_train, y= y_train, cv = 10)
accuracies.mean()

0.48883652178046055

## Training the Random Forest Classification model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 614   51  159]
 [  15  428   59]
 [  69   59 2173]]


0.8864074993107252

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X = X_train, y= y_train, cv = 10)
accuracies.mean()

0.8813750802062786

In [ ]:
accuracies.std()

0.005601563983922356

## **2. Sentiment Polarity** 

In [ ]:
dataset.head(10)

App  ... Sentiment_Subjectivity
0   10 Best Foods for You  ...               0.533333
1   10 Best Foods for You  ...               0.288462
3   10 Best Foods for You  ...               0.875000
4   10 Best Foods for You  ...               0.300000
5   10 Best Foods for You  ...               0.300000
6   10 Best Foods for You  ...               0.900000
8   10 Best Foods for You  ...               0.000000
9   10 Best Foods for You  ...               0.000000
10  10 Best Foods for You  ...               0.600000
11  10 Best Foods for You  ...               0.100000

[10 rows x 5 columns]

In [ ]:
y_poly = dataset.iloc[:, 3].values

In [ ]:
for i in range(len(y_poly)):
  y_poly[i] = y_poly[i]*100
  y_poly[i] = int(y_poly[i])

In [ ]:
print(y_poly)

[100.  25.  40. ...  28.   0.  18.]


Spliting into training and test sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_poly, test_size = 0.2, random_state = 0)

Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
as1 = accuracy_score(y_test, y_pred)
print(cm)
print(as1)

[[12  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  4 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 74]]
0.46098704163220294


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(classifier, X = X_train, y= y_train, cv = 10)
accuracies.mean()

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown

0.45030395209011626